### ISSUE TITLE
Flag of Libya

### ISSUE THREAD

**Issue by jonatanklosko** [kristianmandrup/world-flags#20] opened 2017-11-06 17:44 UTC
The current flag is fully green, whereas it should be red-black-green with a logo. See what [Wikipedia](https://en.wikipedia.org/wiki/Flag_of_Libya) has to say about this.

**Comment by kristianmandrup** [comment] 2017-11-06 18:05
Sorry, I just copied what I found in the icon distributions online. Feel free to fix it! thanks :)

**Comment by viroulep** [comment] 2017-11-08 11:09
Why would you close the issue? :s
The flag is clearly outdated and leaving it open is the best way to have someone know about it and maybe fix it.

We have several members of our organization who are from Libya and would like it to be updated to the correct one, so we can probably help with that.
There is a version of the flag [here](http://www.iconspedia.com/icon/libya-icon-38901.html) (with a 64 png), which looks like it would fit in this collection.

Any suggestions on what are the steps we should follow to make the change?
My wild guess would be that we need to modify the `flags64(_semi).png`, and then resizing it through convert as indicated in the readme?
Since we would just replace an existing flag, would we need to generate adjusted css files too?

**Comment by kristianmandrup** [comment] 2017-11-08 11:30
Awesome! You are right ;) Let's get the fix made. I will look I to it now. Thanks :)

**Comment by viroulep** [comment] 2017-11-08 12:47
Awesome thanks!

Let us know if we can be of any help!

**Comment by kristianmandrup** [comment] 2017-11-08 14:55
Please see latest [flag-fixes branch](https://github.com/kristianmandrup/world-flags/tree/flag-fixes)

Also see notes in `Readme` file. Let me know how it works out and feel free to add better icons to suit your needs. Would love to see a clean fix to this!

**Comment by kristianmandrup** [comment] 2017-11-08 15:26
I would advise you to clone this repo, then link your bundle config to your local clone and debug/work from there... what I always do. Then make any fixes/patches in a PR, then I will merge with master and make new release when you have confirmed all works on your side.

**Comment by viroulep** [comment] 2017-11-08 21:13
I'm realizing that the current master is not quit working with the asset pipeline!
We've actually been using [this fork](https://github.com/world-flags/world-flags) which seems to be working out of the box.

Currently in our Rails setup the SASS is complaining that it can't import `flags/flags16' because there are two candidates file matching. The above fork seemed to have resolved that by only letting the [scss](https://github.com/world-flags/world-flags/tree/master/app/assets/stylesheets/flags) remain.

Not sure where to proceed from here, the best may be to include his changes in this repo?

**Comment by kristianmandrup** [comment] 2017-11-08 22:24
Yeah, I would do that for sure. I don't recall why I used to have both `scss` and `css` files there. If so, they should be moved to separate container folders I guess. Feel free to merge forks or tweak as you see fit and then update the docs. Good luck :)

**Comment by kristianmandrup** [comment] 2017-11-09 06:39
I pushed some fixes to the pipeline conflicts and updated `Readme`. Looking better ;)

**Closed** 2020-01-18 09:13 UTC
